### ISSUE TITLE
Feature Request: Allow encoding into a buffer of bytes

### ISSUE THREAD

**Issue by phayes** [fbernier/base62#6]
I have a use-case where I want to encode some bytes to base62 for use with the [tinystr](https://github.com/zbraniecki/tinystr) crate. Would it be possible to add an `encode_to_bytes_buffer` function that would take a `&mut [u8; N]` buffer to write into?  This way we could do base62 encoding without any allocation.

**Comment by fbernier** [comment]
Hey, that sounds like a legitimate request.

Looking at the doc of tinystr, if the slice has extra bytes available after writing the full result, these bytes need to be zeroed right?

At first glance it doesn't seem like to big of a change but I'll know for sure once I try to do it. Unfortunately, it will not be this weekend. I'm open to PRs until then though!

**Comment by phayes** [comment]
Thanks @fbernier,

I got this far, then realized I don't know enough about using raw-pointers to safely modify `internal_encoder_fn` for a `&[u8]`

```rust
pub fn encode_bytes<T: Into<u128>>(num: T,  buf: &mut [u8]) -> Result<(), DecodeError> {
    let num = num.into();
    let digits = digit_count(num);

    if buf.len() < digits {
        return Err(DecodeError::BufferTooSmall);
    }
    unsafe {
        ...
    }
}
```

**Comment by fbernier** [comment]
@phayes I just gave it a quick try and I think I got it to work. I still need to clean it up, add proper testing and think about the potential safety issues of the implementation but I think it's gonna be fine. It's here for now: https://github.com/fbernier/base62/pull/7/files

**Comment by fbernier** [comment]
Do you think we should write zeros to the rest of the buffer or let the library user zero their own buffer before passing it to the function?

**Comment by phayes** [comment]
> Do you think we should write zeros to the rest of the buffer?

That is a *very* good question.    I'm waffling on what the right answer is here.  I could go either way.   We *are* passing back the number of bytes written, so the caller could zero the rest on their own.  

I think if I had to make a call here, I would say that `encode_bytes` is a fairly low-level API and just document that non-significant bytes are left as-is.

**Comment by ChaiTRex** [comment]
I think that zero-filling is not a good idea, as it's extra work, NUL-termination isn't a thing in Rust (so if you write the resulting filled-in buffer to a file, it will write the NUL bytes as well because they're not considered string terminators), and the caller can easily take the returned length to get the proper subslice.

I think that we should think about having a `std` feature for the crate, where the `std` version of this function takes anything that implements `std::io::Write` and the non-`std` version has exactly the same signature, except that it explicitly takes `&mut [u8]` instead of just any `std::io::Write` implementor.

We might also think about gating the `String`-based functions behind an `alloc` feature of our crate. Maybe `alloc` would be in the default features, `std` wouldn't be.

That way, people who want `no_std` without allocation can get the `&mut [u8]` version of the encoding functions and the `AsRef<[u8]>` version of the decoding functions, letting them do their work without any allocations. People who want `no_std` with allocation (the default) can additionally get the `String` versions. People who want `std` can additionally get the `std::io::Write` versions.

**Comment by phayes** [comment]
@ChaiTRex , does accepting a `std::io::Write` instead of a `&mut [u8]` have any implications on the unsafe pointer stuff that is happening?

**Comment by ChaiTRex** [comment]
Actually, I made an error earlier. The `std::io::Result` would be returned by the `Write` object itself, not our functions, and so we could have our own return type independent of that that's used for both `no_std` and `std` modes.

---

@phayes The simplest change would have the unsafe pointer stuff write to a `[u8; 21]` or something like that and then copy its contents to the `Write`/`&mut [u8]` value. I'd imagine there are slightly more complex ways that would be more efficient, but it shouldn't be too hard to wrap it safely.

**Comment by ChaiTRex** [comment]
The main idea behind the `unsafe` stuff is that we get the base 62 digits starting from the right-side end rather than from the left-side end.

That means we can't simply append bytes left-to-right, we have to figure out the length of the result ahead of time, and then write bytes right-to-left.

The main things that introduce unsafety are:

* every byte the `String` contains within its length **must** be written to before there's the slightest possibility it's ever read from
* every byte written must be within the allocated space for the `String`

The `unsafe fn` code properly handles the first part by writing to *every* new byte included in the longer resulting length and the `String` can't be touched by other code until the `unsafe fn` returns. The calling function has to handle the allocation/reallocation part to ensure the `String` has the capacity to hold the new bytes.
